// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quantum.Data.Context;

#nullable disable

namespace Quantum.Data.Migrations
{
    [DbContext(typeof(PostgreSqlContext))]
    partial class PostgreSqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Quantum.Data.Model.Note", b =>
                {
                    b.Property<Guid>("Note_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Header")
                        .HasColumnType("text")
                        .HasColumnName("header");

                    b.HasKey("Note_Id")
                        .HasName("note_pkey");

                    b.ToTable("Notes", (string)null);

                    b.HasData(
                        new
                        {
                            Note_Id = new Guid("699286ae-38c6-4857-ac76-416f7a53ca19"),
                            Content = "Note 1 Content",
                            Created = new DateTime(2023, 9, 26, 23, 35, 57, 49, DateTimeKind.Local).AddTicks(6425),
                            Header = "Note 1 Header"
                        },
                        new
                        {
                            Note_Id = new Guid("75712383-e4cf-4f24-bd7b-d58f8146672a"),
                            Content = "Note 2 Content",
                            Created = new DateTime(2023, 9, 27, 23, 35, 57, 49, DateTimeKind.Local).AddTicks(6463),
                            Header = "Note 2 Header"
                        },
                        new
                        {
                            Note_Id = new Guid("f0110bd3-5f88-4506-a588-8a8a39fa2857"),
                            Content = "Note 3 Content",
                            Created = new DateTime(2023, 9, 28, 23, 35, 57, 49, DateTimeKind.Local).AddTicks(6466),
                            Header = "Note 3 Header"
                        },
                        new
                        {
                            Note_Id = new Guid("65e36e51-b7a3-41f2-a66c-1cd1bf527944"),
                            Content = "Note 4 Content",
                            Created = new DateTime(2023, 9, 29, 23, 35, 57, 49, DateTimeKind.Local).AddTicks(6468),
                            Header = "Note 4 Header"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
